export const START_REGISTRATION = 'START_REGISTRATION';
export const COMPLETE_REGISTRATION = 'COMPLETE_REGISTRATION';
export const SUBMIT_SEARCH = 'SUBMIT_SEARCH';
export const UPDATE_LOCATION = 'UPDATE_LOCATION';
export const UPDATE_ARRIVAL_DATE = 'UPDATE_ARRIVAL_DATE';
export const UPDATE_DEPARTURE_DATE = 'UPDATE_DEPARTURE_DATE';
export const PROCESS_SEARCH_RESULTS = 'PROCESS_SEARCH_RESULTS';
